// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bb.domain.ref;

import com.bb.domain.ref.RefPaymentTxType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RefPaymentTxType_Roo_Configurable {
    
    declare @type: RefPaymentTxType: @Configurable;
    
}
