// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bb.domain.ref;

import com.bb.domain.ref.RefPaymentType;

privileged aspect RefPaymentType_Roo_JavaBean {
    
    public String RefPaymentType.getName() {
        return this.name;
    }
    
    public void RefPaymentType.setName(String name) {
        this.name = name;
    }
    
}
