// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bb.domain.ref;

import com.bb.domain.ref.RefSex;

privileged aspect RefSex_Roo_JavaBean {
    
    public String RefSex.getName() {
        return this.name;
    }
    
    public void RefSex.setName(String name) {
        this.name = name;
    }
    
}
