// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bb.domain;

import com.bb.domain.CustomerTransaction;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerTransaction_Roo_Configurable {
    
    declare @type: CustomerTransaction: @Configurable;
    
}
