// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bb.domain;

import com.bb.domain.CustomerAvatar;

privileged aspect CustomerAvatar_Roo_JavaBean {
    
    public String CustomerAvatar.getFileName() {
        return this.fileName;
    }
    
    public void CustomerAvatar.setFileName(String fileName) {
        this.fileName = fileName;
    }
    
}
